[c]
compiler = "gcc"
source_files = ["src/main.c"]
flags = []

[assembly]
assembler = "nasm"
source_files = ["src/add.asm"]
flags = ["-f", "elf64"]

[linker]
linker = "gcc"
flags = []

[output]
object_file_directory = "obj"
executable = "bin/demo"